<?php

namespace Proxies\__CG__\Makoto\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Post extends \Makoto\AdminBundle\Entity\Post implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'id', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'title', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'alias', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'author', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'postCategory', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'categoryId', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'postTag', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'body', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'preview', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'date');
        }

        return array('__isInitialized__', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'id', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'title', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'alias', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'author', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'postCategory', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'categoryId', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'postTag', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'body', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'preview', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Post' . "\0" . 'date');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Post $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlias($alias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlias', array($alias));

        return parent::setAlias($alias);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlias', array());

        return parent::getAlias();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthor($author)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthor', array($author));

        return parent::setAuthor($author);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthor', array());

        return parent::getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostCategory($postCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostCategory', array($postCategory));

        return parent::setPostCategory($postCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostCategory', array());

        return parent::getPostCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostTag($postTag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostTag', array($postTag));

        return parent::setPostTag($postTag);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostTag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostTag', array());

        return parent::getPostTag();
    }

    /**
     * {@inheritDoc}
     */
    public function setBody($body)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBody', array($body));

        return parent::setBody($body);
    }

    /**
     * {@inheritDoc}
     */
    public function getBody()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBody', array());

        return parent::getBody();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreview($preview)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreview', array($preview));

        return parent::setPreview($preview);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreview', array());

        return parent::getPreview();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getBodyFormatter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBodyFormatter', array());

        return parent::getBodyFormatter();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
