<?php

namespace Proxies\__CG__\Makoto\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Slider extends \Makoto\AdminBundle\Entity\Slider implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Slider' . "\0" . 'id', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Slider' . "\0" . 'headTitle', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Slider' . "\0" . 'bigTitle', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Slider' . "\0" . 'smallTitle', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Slider' . "\0" . 'orderId', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Slider' . "\0" . 'media');
        }

        return array('__isInitialized__', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Slider' . "\0" . 'id', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Slider' . "\0" . 'headTitle', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Slider' . "\0" . 'bigTitle', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Slider' . "\0" . 'smallTitle', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Slider' . "\0" . 'orderId', '' . "\0" . 'Makoto\\AdminBundle\\Entity\\Slider' . "\0" . 'media');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Slider $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeadTitle($headTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeadTitle', array($headTitle));

        return parent::setHeadTitle($headTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeadTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeadTitle', array());

        return parent::getHeadTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setBigTitle($bigTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBigTitle', array($bigTitle));

        return parent::setBigTitle($bigTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getBigTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBigTitle', array());

        return parent::getBigTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSmallTitle($smallTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSmallTitle', array($smallTitle));

        return parent::setSmallTitle($smallTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getSmallTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSmallTitle', array());

        return parent::getSmallTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderId($orderId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderId', array($orderId));

        return parent::setOrderId($orderId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderId', array());

        return parent::getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedia($media)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedia', array($media));

        return parent::setMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedia', array());

        return parent::getMedia();
    }

}
